 - name: Deploy NodeJs application on remote machine
   hosts: local
   tasks:
   - name: Perform sudo apt update
     become: True
     become_user: root
     apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
   - name: Insatll NodeJs and npm
     become: True
     become_user: root
     apt:
       pkg:
       - nodejs
       - npm

---
# Deploy nodejs application tar file
- name: Deploy NodeJs application
  hosts: local
  tasks:
  - name: Copy and unpack tar file
    unarchive:
      src: /home/pankaj/data/nodejs-app-1.0.0.tgz   #Source is local machine. Unarchieve will copy file to remote, and will then untar it.
      dest: /home/pankaj
  - name: Install dependencies using npm
    community.general.npm:
      path: /home/pankaj/package
  - name: Start the application
    ansible.builtin.command: 
      chdir: /home/pankaj/package
      cmd: node server
    async: 1000  #To run command in ansynchronous manner. Otherwise our playbook execution would never stop.
    poll: 0
  - name: Check if application is running
    ansible.builtin.shell:
      cmd: ps aux | grep node
      register: app_status #We defined a variable here, which will store the output of cmd. As the command is executed on remote, it is not possible to check its status directly.
  - debug: msg={{app_status
  }}  
    
