- name: Deploy and configure nginx web server
  hosts: local
  tasks: 
  - name: Install nginx server
    become: True
    become_user: root
    apt: 
    #To install specific version
      name: nginx=1.18.0-0ubuntu1
      state: present
    #To specify version in regular expression
     #name: nginx=1.17* 
 #To install latest version of nginx
      #name: nginx
      #state: latest
  - name: Start nginx server
    become: True
    become_user: root
    service:
      name: nginx
      state: started