- name: Uninstall nginx web server
  hosts: local
  vars:
  - MAIN_PATH: /home/ansible
  tasks:
  - name: Stop nginx server
    become: True
    become_user: root
    service:
      name: nginx
      state: stopped
  - name: Remove nginx server
    become: True
    become_user: root
    apt: 
      name: nginx
      state: absent
  - name: Delete copied files
    file:
      state: absent
      path: "{{MAIN_PATH}}/package"
    