- name: Uninstall nginx web server
  hosts: local
  tasks: 
  - name: Stop nginx server
    become: True
    become_user: root
    service:
      name: nginx
      state: stopped
  - name: Remove nginx server
    become: True
    become_user: root
    apt: 
      name: nginx
      state: absent  